name: CI Extreme

on:
  push:
    branches:
      - vic/extreme
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.ref_name == 'main' && github.sha || 'anysha' }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: 1

jobs:
  check-compile-macos:
    name: Check macOS compilation
    runs-on: macos-latest-xlarge
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
          targets: aarch64-apple-darwin,x86_64-apple-darwin

      - name: Configure CI
        run: |
          mkdir -p ./../.cargo
          cp ./.cargo/ci-config.toml ./../.cargo/config.toml

      - name: Check that Cargo.lock is up to date
        run: |
          cargo update --locked --workspace

      # TODO: Fix all build issues
      # - name: All steps commented out
      #   run: echo "TODO - all steps commented out for now"
        
      # - name: cargo clippy
      #   run: ./script/clippy
      
      - name: Build
        run: cargo build

      - name: Run tests
        uses: ./.github/actions/run_tests
        
      # Since the macOS runners are stateful, so we need to remove the config file to prevent potential bug.
      - name: Clean CI config file
        if: always()
        run: rm -rf ./../.cargo
        